/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.61"

    id("idea")

    id("org.owasp.dependencycheck") version "5.2.4"

    id("com.github.ben-manes.versions") version "0.27.0"

//    id("de.fayard.buildSrcVersions") version "0.7.0"
    id("de.fayard.refreshVersions") version "0.8.6"

    id("se.patrikerdes.use-latest-versions") version "0.2.13"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

tasks.check {
    dependsOn(tasks.dependencyCheckAggregate)
    dependsOn("refreshVersions")
}

// https://www.youtube.com/watch?v=_s-0MbA5Gvw
dependencyCheck {
    analyzers(delegateClosureOf<org.owasp.dependencycheck.gradle.extension.AnalyzerExtension> {
        assemblyEnabled= false
        nugetconfEnabled = false
        nuspecEnabled = false
        nodeEnabled = false
        nodeAuditEnabled = false
        swiftEnabled = false
        bundleAuditEnabled = false
        rubygemsEnabled = false
        golangDepEnabled = false
        golangModEnabled = false
        pyDistributionEnabled = false
        pyPackageEnabled = false
    })
}

application {
    // Define the main class for the application.
    mainClassName = "study.AppKt"
}

tasks.wrapper {
    gradleVersion = "6.0.1"
    distributionType = Wrapper.DistributionType.ALL
}
