import org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper

//import com.google.protobuf.gradle.GenerateProtoTask

val kotlinVersion = plugins.getPlugin(KotlinPluginWrapper::class.java).kotlinPluginVersion
//val kotlinVersion by extra { "1.2.0-rc-39" }
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
//    id("org.jetbrains.kotlin.jvm") version "1.3.61"
    kotlin("jvm") version "1.3.61"

    idea

    id("org.owasp.dependencycheck") version "5.2.4"

    id("com.github.ben-manes.versions") version "0.27.0"

//    id("de.fayard.buildSrcVersions") version "0.7.0"
    id("de.fayard.refreshVersions") version "0.8.6"

    id("se.patrikerdes.use-latest-versions") version "0.2.13"


    id("com.google.protobuf") version "0.8.8"
    // Apply the application plugin to add support for building a CLI application.
    application

    java
}


repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")


    compileOnly("javax.annotation:javax.annotation-api:1.2")
}

tasks.check {
    dependsOn(tasks.dependencyCheckAggregate)
    dependsOn("refreshVersions")
}

dependencyCheck {
    analyzers(delegateClosureOf<org.owasp.dependencycheck.gradle.extension.AnalyzerExtension> {
        assemblyEnabled = false
        nugetconfEnabled = false
        nuspecEnabled = false
        nodeEnabled = false
        nodeAuditEnabled = false
        swiftEnabled = false
        bundleAuditEnabled = false
        rubygemsEnabled = false
        golangDepEnabled = false
        golangModEnabled = false
        pyDistributionEnabled = false
        pyPackageEnabled = false
    })
}

application {
    // Define the main class for the application.
    mainClassName = "study.AppKt"
}

tasks.wrapper {
    gradleVersion = "6.0.1"
    distributionType = Wrapper.DistributionType.ALL
}



//---------------------------------------
// grpc.
//---------------------------------------

apply(from = "grpc.gradle")

repositories {
    google()
    jcenter()
    mavenCentral()
    mavenLocal()
}



dependencies {

//    extra["grpcVersion"]= "1.25.0"   // CURRENT_GRPC_VERSION
    val grpcVersion by extra("1.25.0")   // CURRENT_GRPC_VERSION
//    val grpcVersion : String by extra   // CURRENT_GRPC_VERSION
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
    implementation(kotlin("stdlib"))
    implementation("io.grpc:grpc-netty-shaded:${grpcVersion}")
    implementation("io.grpc:grpc-protobuf:${grpcVersion}")
    implementation("io.grpc:grpc-stub:${grpcVersion}")
    compileOnly("javax.annotation:javax.annotation-api:1.2")

    testImplementation("io.grpc:grpc-testing:${grpcVersion}")  // gRCP testing utilities
    testImplementation("junit:junit:4.12")
    testImplementation("org.mockito:mockito-core:2.28.2")
}
//plugins.findPlugin("com.google.protobuf"). {

// https://github.com/rouzwawi/grpc-kotlin-1/blob/master/build.gradle.kts
//protobuf {
//      withGroovyBuilder {
//    "protobuf" {
//      "protoc" {
//        "setArtifact"("com.google.protobuf:protoc:3.6.1")
//      }
//      "plugins" {
//        "create"("grpc-kotlin") {
//          "setArtifact"("io.rouz:grpc-kotlin-gen:0.0.5:jdk8@jar")
//        }
//        "create"("grpc-java") {
//          "setArtifact"("io.grpc:protoc-gen-grpc-java:1.14.0")
//        }
//      }
//    }
//  }
//  tasks.withType<GenerateProtoTask> {
//    plugins.create("grpc-kotlin")
//    plugins.create("grpc-java")
//  }
//}
//kotlin {
//}


//        protoc { artifact = "com.google.protobuf:protoc:3.11.0" }
//        plugins {
//            grpc { artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}" }
//        }
//        generateProtoTasks {
//            all() * . plugins { grpc {} }
//        }
//}

//startScripts.enabled = false
//
//task helloWorldServer(type: CreateStartScripts) {
//    mainClassName = 'io.grpc.examples.helloworld.HelloWorldServer'
//    applicationName = 'hello-world-server'
//    outputDir = new File(project.buildDir, 'tmp')
//    classpath = startScripts.classpath
//}
//
//task helloWorldClient(type: CreateStartScripts) {
//    mainClassName = 'io.grpc.examples.helloworld.HelloWorldClient'
//    applicationName = 'hello-world-client'
//    outputDir = new File(project.buildDir, 'tmp')
//    classpath = startScripts.classpath
//}
//
//applicationDistribution.into('bin') {
//    from(helloWorldServer)
//    from(helloWorldClient)
//    fileMode = 0755
//}

