/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.0.1/userguide/multi_project_builds.html
 */

rootProject.name = "hello-kotlin"
include("kotlin-study", "hello-grpc")
pluginManagement {
    repositories {
        google()
        jcenter()
        maven( // The google mirror is less flaky than mavenCentral()
            url = "https://maven-central.storage-download.googleapis.com/repos/central/data/"
        )
        gradlePluginPortal()
    }
}
plugins {
    id("com.gradle.enterprise").version("3.1")
}
gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
    }
}
